---
name: "Mehmet"
surname: "Kutluay"
position: "Lead Data Scientist"
address: "Rotterdam - The Netherlands"
phone: +31 685478120
email: "mehkutluay@gmail.com"
github: "YMehmetKutluay"
linkedin: "mehmet-kutluay-phd"
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
```

# Skills

## Data Science

* Network Analytics, Anomaly Detection, Docker, Spark, Time Series Forecasting, Cross-Sectional Prediction,  Data Visualization, ETL, Remote Sensing

## Languages

* Statistics/Data Science: Python, R, SQL, Matlab

* Other: Markdown, Microsoft Office


# Experience

```{r}
# Define information on Knab Lead DS
Knab_lead <- c("Lead Data Scientist", "Knab", "March 2024 - Present", "Amsterdam")
# Define information on Knab
Knab <- c("Senior Data Scientist", "Knab", "August 2023 - March 2024", "Amsterdam")
# Define information on Apollo Agriculture
Apollo <- c("Senior Data Scientist", "Apollo Agriculture", "May 2022 - April 2023", "Amsterdam")
# Define information on TMNL
TMNL <- c("Senior Data Scientist", "Transactie Monitoring Nederland", "May 2021 - April 2022", "Purmerend")
# Define information on FEC
ING_fec <- c("Data Scientist", "ING Bank N.V. - Financial Crime Analytics", "Nov 2019 - April 2021", "Amsterdam")
# Define information on Finance Analytics
ING_finance <- c("Data Scientist", "ING Bank N.V. - Finance Analytics", "Feb 2018 - Oct 2019", "Amsterdam")
# Define information on PhD
phd <- c("PhD Researcher in Environmental Economics", "VU University Amsterdam", "Sep 2014 - Aug 2018", "Amsterdam")
# Define information on teaching assistant
teaching_assistant <- c("Teaching Assistant", "VU University Amsterdam / Tinbergen Institute", "Sep 2013 - Feb 2018", "Amsterdam")
# Combine all information
tribble(
  ~ role, ~ company, ~ dates, ~ loc, ~ details,
  # Knab lead
  Knab_lead[1], Knab_lead[2], Knab_lead[3], Knab_lead[4],
  "Leading a team of 6-7 data scientists, while also working on model development and productionization.",
  Knab_lead[1], Knab_lead[2], Knab_lead[3], Knab_lead[4],
  "Responsible for moulding and executing the ML / AI strategy of Knab, as well as mentoring other data scientists and leading by example.",
  # Knab
  Knab[1], Knab[2], Knab[3], Knab[4],
  "In a team of 6-7 data scientists, working mainly on financial crime analytics products. Infrastructure environment: AWS and on-premise clusters",
  Knab[1], Knab[2], Knab[3], Knab[4],
  "Helping to launch first models in production for the data science team, working with different senior stakeholders in the bank (including data engineering and model risk management) to make this process smoother",
  Knab[1], Knab[2], Knab[3], Knab[4],
  "Setting up standardized way of working for the team, creating and maintaining Python microservices",
  # Apollo
  Apollo[1], Apollo[2], Apollo[3], Apollo[4],
  "In a small team (4-5 FTE's) of data scientists, working on multiple projects with different stakeholders. These are fraud detection, credit risk scoring and satellite image database creation. Infrastructure environment: AWS",
  Apollo[1], Apollo[2], Apollo[3], Apollo[4],
  "Launched and monitored multiple models in production - both batch processes and real-time applications",
  Apollo[1], Apollo[2], Apollo[3], Apollo[4],
  "Helping set up the way-of-working framework (Docker for local development, setting coding standards, creating/maintaining Python microservices etc.)",
  Apollo[1], Apollo[2], Apollo[3], Apollo[4],
  "Optimizing existing models by including extensive unit/integration tests, speeding up ETL with Dask",
  # TMNL
  TMNL[1], TMNL[2], TMNL[3], TMNL[4],
  "In multifunctional department, consisting of data scientists and anti-money laundering experts",
  TMNL[1], TMNL[2], TMNL[3], TMNL[4],
  "Creating/maintaining two Python packages for network analytics projects: 1. efficient network traversals and 2. detecting communities within networks. Infrastructure environment: AWS",
  TMNL[1], TMNL[2], TMNL[3], TMNL[4],
  "Main linking pin with engineering teams to ensure a workable framework for model development. Actively helping with setting up a feature store and spreading good Spark practices",
  TMNL[1], TMNL[2], TMNL[3], TMNL[4],
  "Integrating anti-money laundering experts actively into analytics projects",
  TMNL[1], TMNL[2], TMNL[3], TMNL[4],
  "Participating in high-level discussions on day-to-day and strategic topics",
  # ING FEC
  ING_fec[1], ING_fec[2], ING_fec[3], ING_fec[4],
  "Part of a big team of 20-25 FTE's that develop models to detect money laundering and other illegal financial activities",
  ING_fec[1], ING_fec[2], ING_fec[3], ING_fec[4],
  "Creating two Python packages for: 1. streamlined unsupervised anomaly detection and 2. extracting network features from transaction data Infrastructure environment: in-house clusters.",
  ING_fec[1], ING_fec[2], ING_fec[3], ING_fec[4],
  "Main machine learning domain: unsupervised anomaly detection (e.g. isolation forest, k-means, outlier variational autoencoder)",
  ING_fec[1], ING_fec[2], ING_fec[3], ING_fec[4],
  "Communicating with other end-users of the Python packages for further development",
  ING_fec[1], ING_fec[2], ING_fec[3], ING_fec[4],
  "Running workshops on day-to-day usage of Docker",
  ING_fec[1], ING_fec[2], ING_fec[3], ING_fec[4],
  "Coaching trainees in data science work",
  # ING finance
  ING_finance[1], ING_finance[2], ING_finance[3], ING_finance[4],
    "Part of a small team of 2-3 FTE's that service employees in Group Finance through analytics projects. All projects are centered around time series data cleaning, wrangling and forecasting. Infrastructure environment: in-house clusters",
  ING_finance[1], ING_finance[2], ING_finance[3], ING_finance[4],
    "Created three R packages for time series forecasting, detecting/correcting anomalies and data exploration",
  ING_finance[1], ING_finance[2], ING_finance[3], ING_finance[4],
    "These R packages are open sourced and maintained by me. Click for \\href{https://github.com/ing-bank/tstools}{tstools}, \\href{https://github.com/ing-bank/tsclean}{tsclean}, \\href{https://github.com/ing-bank/tsforecast}{tsforecast}",
  ING_finance[1], ING_finance[2], ING_finance[3], ING_finance[4],
    "Main machine learning domain: time series forecasting (ARIMA, LSTM, Kalman filter",
  ING_finance[1], ING_finance[2], ING_finance[3], ING_finance[4],
    "Deploying projects via local and docker solutions",
  ING_finance[1], ING_finance[2], ING_finance[3], ING_finance[4],
    "Running workshops and trainings in R, Python and statistics",
  ING_finance[1], ING_finance[2], ING_finance[3], ING_finance[4],
    "Coaching IT trainees in data science work",
  ING_finance[1], ING_finance[2], ING_finance[3], ING_finance[4],
    "Engaging stakeholders to help them become more data-savvy and understand what they can (and can't) do with data science",
  # PhD
  phd[1], phd[2], phd[3], phd[4],
    "Thesis title: 'The Value of (Avoiding) Malaria' (\\href{https://www.dropbox.com/s/0du7immzy1k14o1/PhD_Thesis.pdf?dl=0}{link}, graduated 2nd of May 2019)",
  phd[1], phd[2], phd[3], phd[4],
    "Supervisors: Roy Brouwer \\& Richard Tol",
  phd[1], phd[2], phd[3], phd[4],
    "Links to completed papers:
    \\begin{itemize}
    \\item Valuing malaria morbidity     (\\href{https://www.tandfonline.com/doi/full/10.1080/21606544.2019.1581094}{link})
    \\item Preference updating in public health risk valuation (\\href{https://www.researchgate.net/publication/320234394_Preference_updating_in_public_health_risk_valuation}{link})
    \\item Public preferences and valuation of new malaria risk (\\href{https://www.researchgate.net/publication/320234398_Public_preferences_and_valuation_of_new_malaria_risk}{link}) 
    \\item Attitudes towards public health spending (\\href{https://www.sussex.ac.uk/webteam/gateway/file.php?name=wps-07-2019.pdf&site=24}{link}) 
    \\end{itemize}",
  phd[1], phd[2], phd[3], phd[4],
    "This was financed by an EU FP7 project: HELIX (\\href{https://www.helixclimate.eu/}{link}). This involved multidisciplinary collaboration with researchers from mathematics, physics, engineering, geography and sociology. I organized and executed a field survey in Mumbai, India between March - June 2016 as part of this project. Some analyses of the data from this survey can be found on my GitHub page.",
  # Teaching assistant
  teaching_assistant[1], teaching_assistant[2], teaching_assistant[3], teaching_assistant[4],
    "Courses: Statistics/Econometrics (masters level - including coding in SPSS and R), Mathematics (masters level - linear algebra and advanced calculus)"
  ) %>% 
  detailed_entries(role, loc, company, dates, details, .protect = F)
```

# Education

```{r}
# Define information on Master
MSc_info <- c("MPhil in Economics", "Tinbergen Institute", "Amsterdam/Rotterdam, The Netherlands","Sep 2012 - Aug 2014")
# Define information on Bachelor
BSc_info <- c("BSc in Economics", "Bilkent University", "Ankara, Turkey", "Sep 2008 - Jun 2012")
# Combine all information
tribble(
    ~ degree, ~ uni, ~ loc, ~ dates, ~ details,
    # MSc
    MSc_info[1], MSc_info[2], MSc_info[3], MSc_info[4], 
      "Specialization: Applied micro-econometrics",
    MSc_info[1], MSc_info[2], MSc_info[3], MSc_info[4], 
      "Thesis: 'What explains willingness to pay for avoiding morbidity risk due to malaria? Results from a global meta-analysis' (later on became first chapter of PhD thesis)",
    # BSc
    BSc_info[1], BSc_info[2], BSc_info[3], BSc_info[4], 
      "Specialization: Academic (i.e. a special focus on applied mathematics and statistics)"
  ) %>% 
  detailed_entries(degree, uni, loc, dates, details)
```
